name: Android Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build, Test & Sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STOREPASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEYPASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.9"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Set build version code from run number
        run: |
          version_name=$(grep '^version:' pubspec.yaml | sed 's/version: *//' | cut -d '+' -f1)
          sed -i "s/^version: .*/version: ${version_name}+${{ github.run_number }}/" pubspec.yaml

      - name: Start Android Release Build
        run: flutter build appbundle

      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab

  deploy:
    name: Deploy Android Build
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release
      - name: Release Build to production track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: developer.rohitsaw.split
          releaseFiles: app-release.aab
          track: production
          status: completed
